# frozen_string_literal: true

module ActiveRecord
  module ConnectionAdapters
    module Peasys
      class SchemaCreation < ConnectionAdapters::SchemaCreation
        private

          def add_column_options!(sql, options)
            if options[:auto_increment]
              sql << " GENERATED BY DEFAULT AS IDENTITY"
            end

            if options[:null] == false
              sql << " NOT NULL"
            end

            if options.key?(:default) && !options[:auto_increment]
              sql << " DEFAULT #{quote_default_expression(options[:default], options[:column])}"
            end

            sql
          end
      end
    end
  end
end
