# frozen_string_literal: true

require_relative "../test_helper"

class AdapterTest < Minitest::Test
  def test_adapter_name
    assert_equal "Peasys", ActiveRecord::ConnectionAdapters::PeasysAdapter::ADAPTER_NAME
  end

  def test_adapter_is_registered
    # Rails 7.2 registration
    adapters = ActiveRecord::ConnectionAdapters.instance_variable_get(:@adapters)
    assert adapters.key?("peasys"), "Adapter 'peasys' should be registered"
  end

  def test_native_database_types
    types = ActiveRecord::ConnectionAdapters::PeasysAdapter::NATIVE_DATABASE_TYPES

    assert_equal({ name: "VARCHAR", limit: 255 }, types[:string])
    assert_equal({ name: "CLOB" }, types[:text])
    assert_equal({ name: "INTEGER" }, types[:integer])
    assert_equal({ name: "BIGINT" }, types[:bigint])
    assert_equal({ name: "DOUBLE" }, types[:float])
    assert_equal({ name: "DECIMAL" }, types[:decimal])
    assert_equal({ name: "TIMESTAMP" }, types[:datetime])
    assert_equal({ name: "TIME" }, types[:time])
    assert_equal({ name: "DATE" }, types[:date])
    assert_equal({ name: "BLOB" }, types[:binary])
    assert_equal({ name: "SMALLINT" }, types[:boolean])
    assert_equal({ name: "CLOB" }, types[:json])
  end

  def test_primary_key_type
    types = ActiveRecord::ConnectionAdapters::PeasysAdapter::NATIVE_DATABASE_TYPES
    assert_equal "INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY", types[:primary_key]
  end

  def test_type_map_varchar
    type_map = ActiveRecord::ConnectionAdapters::PeasysAdapter::TYPE_MAP
    result = type_map.lookup("VARCHAR(255)")
    assert_kind_of ActiveModel::Type::String, result
  end

  def test_type_map_integer
    type_map = ActiveRecord::ConnectionAdapters::PeasysAdapter::TYPE_MAP
    result = type_map.lookup("INTEGER")
    assert_kind_of ActiveModel::Type::Integer, result
    assert_equal 4, result.limit
  end

  def test_type_map_smallint
    type_map = ActiveRecord::ConnectionAdapters::PeasysAdapter::TYPE_MAP
    result = type_map.lookup("SMALLINT")
    assert_kind_of ActiveModel::Type::Integer, result
    assert_equal 2, result.limit
  end

  def test_type_map_bigint
    type_map = ActiveRecord::ConnectionAdapters::PeasysAdapter::TYPE_MAP
    result = type_map.lookup("BIGINT")
    assert_kind_of ActiveModel::Type::Integer, result
    assert_equal 8, result.limit
  end

  def test_type_map_clob_is_text
    type_map = ActiveRecord::ConnectionAdapters::PeasysAdapter::TYPE_MAP
    result = type_map.lookup("CLOB")
    assert_kind_of ActiveRecord::Type::Text, result
  end

  def test_type_map_timestamp_is_datetime
    type_map = ActiveRecord::ConnectionAdapters::PeasysAdapter::TYPE_MAP
    result = type_map.lookup("TIMESTAMP")
    assert_kind_of ActiveRecord::Type::DateTime, result
  end

  def test_type_map_blob_is_binary
    type_map = ActiveRecord::ConnectionAdapters::PeasysAdapter::TYPE_MAP
    result = type_map.lookup("BLOB")
    assert_kind_of ActiveModel::Type::Binary, result
  end

  def test_type_map_double_is_float
    type_map = ActiveRecord::ConnectionAdapters::PeasysAdapter::TYPE_MAP
    result = type_map.lookup("DOUBLE")
    assert_kind_of ActiveModel::Type::Float, result
  end

  def test_type_map_decimal
    type_map = ActiveRecord::ConnectionAdapters::PeasysAdapter::TYPE_MAP
    result = type_map.lookup("DECIMAL")
    assert_kind_of ActiveModel::Type::Decimal, result
  end

  def test_feature_flags
    adapter_class = ActiveRecord::ConnectionAdapters::PeasysAdapter

    assert adapter_class.method_defined?(:supports_migrations?)
    assert adapter_class.method_defined?(:supports_foreign_keys?)
    assert adapter_class.method_defined?(:supports_views?)
    assert adapter_class.method_defined?(:supports_common_table_expressions?)
    assert adapter_class.method_defined?(:supports_check_constraints?)
    assert adapter_class.method_defined?(:supports_comments?)
    assert adapter_class.method_defined?(:supports_insert_returning?)
  end
end
